# Required
version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"

  commands:
    # Generate API reference manually
    - cd docs
    - python -m sphinx-apidoc -o source/api ../src/alpheast -f -e
    - cd ..

# Build documentation in the "docs/" directory with Sphinx
sphinx:
   configuration: docs/source/conf.py

# Install project dependencies and the project itself
python:
   install:
   - method: pip
     path: .
   - requirements: docs/requirements.txt