version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"

  commands:
    # Generate API reference manually
    - pip install -r docs/requirements.txt
    - pip install .

    - sphinx-apidoc -o docs/source/api src/alpheast -f -e

    # Build
    - sphinx-build -b html docs/source docs/build/html

    - mkdir -p "$READTHEDOCS_OUTPUT/html" 
    - cp -r docs/build/html/. "$READTHEDOCS_OUTPUT/html/"
    - rm -rf docs/build

sphinx:
   configuration: docs/source/conf.py
   
   