"""Create eod_prices table and enable hypertable

Revision ID: 1b0e1ef46d5e
Revises: 
Create Date: 2025-06-07 12:03:14.772255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b0e1ef46d5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eod_prices',
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('open', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('high', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('low', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('close', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('time', 'symbol')
    )
    # ### end Alembic commands ###

    op.execute("SELECT create_hypertable('eod_prices', 'time', chunk_time_interval => INTERVAL '1 day', if_not_exists => TRUE);")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eod_prices')
    # ### end Alembic commands ###
