"""Create price_bar entity

Revision ID: 4f2b24a97e09
Revises: 0b8856098939
Create Date: 2025-06-08 23:59:47.353518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f2b24a97e09'
down_revision: Union[str, None] = '0b8856098939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_bars',
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('open', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('high', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('low', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('close', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('time', 'symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
