"""Refactor eod_price entity

Revision ID: be134cd2e036
Revises: 1b0e1ef46d5e
Create Date: 2025-06-07 13:09:13.962050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be134cd2e036'
down_revision: Union[str, None] = '1b0e1ef46d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('eod_prices_time_idx'), table_name='eod_prices')
    op.drop_table('eod_prices')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eod_prices',
    sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=15, scale=6), autoincrement=False, nullable=True),
    sa.Column('high', sa.NUMERIC(precision=15, scale=6), autoincrement=False, nullable=True),
    sa.Column('low', sa.NUMERIC(precision=15, scale=6), autoincrement=False, nullable=True),
    sa.Column('close', sa.NUMERIC(precision=15, scale=6), autoincrement=False, nullable=True),
    sa.Column('volume', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('time', 'symbol', name=op.f('eod_prices_pkey'))
    )
    op.create_index(op.f('eod_prices_time_idx'), 'eod_prices', [sa.literal_column('time DESC')], unique=False)
    # ### end Alembic commands ###
